[package]
name = "libnveth"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
lto = "thin" # work around undefined symbol _fltused

[profile.release]
panic = "abort"

[dependencies]
sal = { path = "../sal" }
