use crate::windows::shared::{
    ndis::types::NDIS_STATUS,
    ntstatus::{STATUS_NOT_SUPPORTED, STATUS_SUCCESS},
};

// L14
pub const NDIS_STATUS_SUCCESS: NDIS_STATUS = NDIS_STATUS(STATUS_SUCCESS.0);
pub const NDIS_STATUS_NOT_SUPPORTED: NDIS_STATUS = NDIS_STATUS(STATUS_NOT_SUPPORTED.0);
pub const NDIS_STATUS_INVALID_LENGTH: NDIS_STATUS = NDIS_STATUS(0xC0010014);
pub const NDIS_STATUS_INVALID_DATA: NDIS_STATUS = NDIS_STATUS(0xC0010015);
