[package]
name = "nvnet-client"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
windows = "0.21"

nvnet-shared = { path = "../nvnet-shared" }

[build-dependencies]
windows = "0.21"
