[package]
name = "nvnet"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.120", features = ["derive"] }
serde_yaml = "0.8.15"
winapi = { version = "0.3", features = ["std", "ws2def", "errhandlingapi", "fileapi", "handleapi", "ioapiset", "winbase"] }
